clean:
	rm -r -f ball_bins3/ binary_search/ bst_copy/ closest/ merge_sort/ bubble_sort/ factorial/ fibonacci/ hanoi/ heap_sort/ insertion_sort/ karatsuba/ quick_sort/ selection_sort/ strassen/ subset_sum/
