clean:
	rm -r -f ball_bins3/ binary_search/ bst_copy/ closest/ merge_sort/ bubble_sort/ factorial/ fibonacci/ hanoi/ heap_sort/ inorder/ insertion_sort/ karatsuba/ postorder/ quick_sort/ reverse_stack/ selection_sort/ stack_sort/ strassen/ subset_sum/ ackermann/ bstcopy/ copy/ qsortassert/
